# Generated by Django 5.1.1 on 2025-09-15 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_tests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='medicines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='prescription_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='vaccine_dose',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
