# Generated by Django 5.1.1 on 2025-09-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_diagnosis_visit_dispensed_visit_dispensed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reception_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='department',
            field=models.CharField(blank=True, choices=[('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('OB-GYN', 'OB-GYN'), ('Others', 'Others')], max_length=32),
        ),
    ]
