# Generated by Django 5.1.1 on 2025-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_claimed_at_visit_claimed_by_visit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
