# Generated by Django 5.1.1 on 2025-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visit_lab_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='department',
            field=models.CharField(blank=True, choices=[('Pediatrics', 'Pediatrics (Children’s Health)'), ('OB-GYN', 'Obstetrics and Gynecology (OB-GYN)'), ('Cardiology', 'Cardiology (Heart Care)'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Dermatology', 'Dermatology (Skin Care)'), ('ENT', 'ENT (Ear, Nose, Throat)')], max_length=32),
        ),
    ]
