# Generated by Django 5.1.1 on 2025-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_visit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lab_test_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
