# Generated by Django 5.1.1 on 2025-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_visit_lab_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lab_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
