# Generated by Django 5.1.1 on 2025-09-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_visit_doctor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_department', models.BooleanField(default=False, help_text='Whether this service requires department selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Specific service type selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.servicetype'),
        ),
    ]
