# Generated by Django 5.1.1 on 2025-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_visit_status'),
        ('visits', '0013_visit_status_diagnosis_prescriptionitem'),
    ]

    operations = [
    ]
