# Generated by Django 5.1.1 on 2025-09-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_visit_assigned_to_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(choices=[('Hematology', 'Hematology (Blood Analysis)'), ('Clinical Microscopy', 'Clinical Microscopy (Urine/Stool Exam)'), ('Clinical Chemistry', 'Clinical Chemistry (Blood Chemistry)'), ('Immunology and Serology', 'Immunology and Serology (Infectious Disease Tests)'), ('Microbiology', 'Microbiology (Culture and Sensitivity)'), ('Pathology', 'Pathology (Tissue and Biopsy)')], max_length=64)),
                ('status', models.CharField(choices=[('queue', 'Queue'), ('claimed', 'Claimed'), ('in_process', 'In Process'), ('done', 'Done'), ('not_done', 'Not Done')], default='queue', max_length=32)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result_entries', to='visits.visit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
