# Generated by Django 5.1.1 on 2025-09-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_doctor_specialization'),
        ('visits', '0016_labresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('COVID-19 Vaccine', 'COVID-19 Vaccine'), ('Influenza (Flu) Vaccine', 'Influenza (Flu) Vaccine'), ('Hepatitis B Vaccine', 'Hepatitis B Vaccine'), ('Tetanus Vaccine', 'Tetanus Vaccine'), ('Measles, Mumps, Rubella (MMR) Vaccine', 'Measles, Mumps, Rubella (MMR) Vaccine'), ('Polio Vaccine', 'Polio Vaccine'), ('Varicella (Chickenpox) Vaccine', 'Varicella (Chickenpox) Vaccine'), ('Human Papillomavirus (HPV) Vaccine', 'Human Papillomavirus (HPV) Vaccine')], max_length=64)),
                ('status', models.CharField(choices=[('queue', 'Queue'), ('claimed', 'Claimed'), ('in_process', 'In Process'), ('done', 'Done'), ('not_done', 'Not Done')], default='queue', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='visits.visit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
