# Generated by Django 5.1.1 on 2025-09-20 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_vaccinationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy_notes', models.TextField(blank=True, help_text='Notes from pharmacy staff (substitutions, etc.)')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicines', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='Name of the medicine', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage strength (e.g., 500mg, 10ml)', max_length=100)),
                ('frequency', models.CharField(help_text='How often to take (e.g., 3 times daily, every 8 hours)', max_length=100)),
                ('duration', models.CharField(help_text='How long to take (e.g., 7 days, 2 weeks)', max_length=100)),
                ('quantity', models.CharField(help_text='Quantity to dispense (e.g., 30 tablets, 1 bottle)', max_length=50)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this medicine')),
                ('dispensed_quantity', models.CharField(blank=True, help_text='Actual quantity dispensed', max_length=50)),
                ('substitution_notes', models.TextField(blank=True, help_text='Notes if medicine was substituted')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='visits.prescription')),
            ],
        ),
    ]
