# Generated by Django 5.1.1 on 2025-09-21 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_USER_STATUS', 'Enable/Disable User'), ('CREATE_PATIENT', 'Create Patient'), ('UPDATE_PATIENT', 'Update Patient'), ('DELETE_PATIENT', 'Delete Patient'), ('RESEND_QR_CODE', 'Resend QR Code'), ('CREATE_VISIT', 'Create Visit'), ('UPDATE_VISIT', 'Update Visit'), ('DELETE_VISIT', 'Delete Visit'), ('CREATE_PRESCRIPTION', 'Create Prescription'), ('UPDATE_PRESCRIPTION', 'Update Prescription'), ('DISPENSE_MEDICINE', 'Dispense Medicine'), ('CREATE_LAB_RESULT', 'Create Lab Result'), ('UPDATE_LAB_RESULT', 'Update Lab Result'), ('CREATE_VACCINATION', 'Create Vaccination'), ('UPDATE_VACCINATION', 'Update Vaccination'), ('SYSTEM_ACTION', 'System Action')], max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
