# Generated by Django 5.1.1 on 2025-09-20 17:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0010_alter_doctor_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_doses_required', models.PositiveIntegerField(default=1, help_text='Total number of doses required for complete vaccination', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dose_intervals', models.JSONField(default=list, help_text='List of intervals in days between doses (e.g., [0, 28, 180] for 0, 1 month, 6 months)')),
                ('age_minimum', models.PositiveIntegerField(default=0, help_text='Minimum age in months for this vaccine')),
                ('age_maximum', models.PositiveIntegerField(blank=True, help_text='Maximum age in months for this vaccine (null for no limit)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_vaccinations', to='vaccinations.vaccinetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'vaccine_type')},
            },
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(help_text='Dose number (1st, 2nd, 3rd, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('administered', models.BooleanField(default=False)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('site_of_injection', models.CharField(blank=True, help_text='e.g., Left arm, Right arm', max_length=100)),
                ('adverse_reactions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_doses', to=settings.AUTH_USER_MODEL)),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vaccinations.patientvaccination')),
            ],
            options={
                'ordering': ['dose_number'],
                'unique_together': {('vaccination', 'dose_number')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vaccinations.vaccinedose')),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
    ]
