# Generated by Django 5.1.1 on 2025-09-15 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('reception', 'Receptionist/Triage'), ('doctor', 'Doctor'), ('lab', 'Laboratory Staff'), ('pharmacy', 'Pharmacist'), ('vaccination_staff', 'Vaccination Staff')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
