# Generated by Django 5.1.1 on 2025-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('OB-GYN', 'OB-GYN'), ('Others', 'Others')], max_length=100, verbose_name='Department'),
        ),
    ]
