# Generated by Django 5.1.1 on 2025-09-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
