# Generated by Django 5.1.1 on 2025-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Pediatrics', 'Pediatrics (Children’s Health)'), ('OB-GYN', 'Obstetrics and Gynecology (OB-GYN)'), ('Cardiology', 'Cardiology (Heart Care)'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Dermatology', 'Dermatology (Skin Care)'), ('ENT', 'ENT (Ear, Nose, Throat)')], max_length=100, verbose_name='Department'),
        ),
    ]
