# Generated by Django 5.1.1 on 2025-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Patient profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
