# Generated by Django 5.1.1 on 2025-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Doctor must change password on next login'),
        ),
    ]
