# Generated by Django 5.1.1 on 2025-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_add_doctor_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Doctor must change password on first login'),
        ),
    ]
